version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: teamoctopus/octopus_backend_dev
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db
  
  gateway:
    image: teamoctopus/octopus_gateway_dev
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend      