# Generated by Django 4.1 on 2023-12-11 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_rename_favoriteslist_favorite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "ordering": ("-date_added",),
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранное",
            },
        ),
        migrations.AddField(
            model_name="favorite",
            name="date_added",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата добавления в избранное",
            ),
        ),
    ]
