# Generated by Django 4.1 on 2023-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0007_alter_favorite_options_favorite_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата добавления в избранное"
            ),
        ),
    ]
